CREATE TABLE BOOK(
    BOOK_SEQ DECIMAL PRIMARY KEY,
    TITLE VARCHAR2(40),
    AUTHOR VARCHAR2(20),
    COMPANY VARCHAR2(20)
);
CREATE TABLE USERLIST(
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PW VARCHAR2(20),
    USER_NAME VARCHAR2(20),
    BIRTH VARCHAR2(20),
    R_LEVEL VARCHAR2(20),
    DISCOUNT_RATE DECIMAL,
    RENT VARCHAR2(20)
);
CREATE TABLE RENT(
    RENT_SEQ DECIMAL PRIMARY KEY,
    BOOK_SEQ DECIMAL,
    USER_ID VARCHAR2(20),
    RENT_DATE VARCHAR2(20),
    RETURN_DATE VARCHAR2(20),
    OVERDUE_MONEY VARCHAR2(20)
);

ALTER TABLE RENT ADD CONSTRAINT RENT_FK_BOOK_SEQ FOREIGN KEY (BOOK_SEQ) REFERENCES BOOK (BOOK_SEQ);
ALTER TABLE RENT ADD CONSTRAINT RENT_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERLIST (USER_ID);

SELECT * FROM TAB;

commit;